import 'package:hive/hive.dart';
import 'package:stage_movie/data/models/movie_model.dart';

class LocalMovieDataSource {
  static const String _favoritesBoxName = 'favorites';

  Future<void> initialize() async {
    Hive.registerAdapter(MovieModelAdapter());
    await Hive.openBox<MovieModel>(_favoritesBoxName);
  }

  Future<List<MovieModel>> getFavoriteMovies() async {
    final box = Hive.box<MovieModel>(_favoritesBoxName);
    return box.values.toList();
  }

  Future<bool> toggleFavorite(MovieModel movie) async {
    final box = Hive.box<MovieModel>(_favoritesBoxName);
    final key = movie.id.toString();

    if (box.containsKey(key)) {
      await box.delete(key);
      return false; // Movie was removed from favorites
    } else {
      final updatedMovie = movie.copyWith(isFavorite: true);
      await box.put(key, updatedMovie);
      return true; // Movie was added to favorites
    }
  }

  Future<bool> isFavorite(int movieId) async {
    final box = Hive.box<MovieModel>(_favoritesBoxName);
    return box.containsKey(movieId.toString());
  }
}

// This adapter will be generated by the build_runner
class MovieModelAdapter extends TypeAdapter<MovieModel> {
  @override
  final int typeId = 0;

  @override
  MovieModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return MovieModel(
      id: fields[0] as int,
      title: fields[1] as String,
      overview: fields[2] as String,
      posterPath: fields[3] as String?,
      backdropPath: fields[4] as String?,
      voteAverage: fields[5] as double,
      releaseDate: fields[6] as String?,
      genreIds: (fields[7] as List?)?.cast<int>(),
      isFavorite: fields[8] as bool,
    );
  }

  @override
  void write(BinaryWriter writer, MovieModel obj) {
    writer
      ..writeByte(9)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.title)
      ..writeByte(2)
      ..write(obj.overview)
      ..writeByte(3)
      ..write(obj.posterPath)
      ..writeByte(4)
      ..write(obj.backdropPath)
      ..writeByte(5)
      ..write(obj.voteAverage)
      ..writeByte(6)
      ..write(obj.releaseDate)
      ..writeByte(7)
      ..write(obj.genreIds)
      ..writeByte(8)
      ..write(obj.isFavorite);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MovieModelAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
